### ISSUE TITLE
Already created Integrations via Terraform are not Exposing Integration Key and Webhook URL

### ISSUE THREAD

**Issue by vitulrana** [Zenduty/terraform-provider-zenduty#10]
Resources that were already created by terraform before v0.0.16 was released are not providing `webhook_url` and `integration_key` after we upgrade the provider version.

**Before upgrade `zenduty_integration` attributes** 

```hcl
zenduty_integration = {
  "application" = "1ef0e211-82fb-454a-96c4-20bd26ebdcab"
  "id" = "<UUID>"
  "name" = "Low Priority Alerts"
  "service_id" = "<UUID>"
  "summary" = "Low Priority Alerts from Cloudwatch"
  "team_id" = "<UUID>"
}
```

**After upgrade `zenduty_integration` attributes** 

```hcl
zenduty_integration = {
  "application" = "1ef0e211-82fb-454a-96c4-20bd26ebdcab"
  "create_incident_for" = 1
  "default_urgency" = 1
  "id" = "<UUID>"
  "integration_key" = tostring(null)
  "is_enabled" = true
  "name" = "Low Priority Alerts"
  "service_id" = "<UUID>"
  "summary" = "Low Priority Alerts from Cloudwatch"
  "team_id" = "<UUID>"
  "webhook_url" = tostring(null)
}
```

**Comment by dheeruk12** [comment]
@vitulrana 
Run `terraform plan` to sync the resources and then paste the **integration_key** and **webhook_url** in the resource block.This is required  to support version upgrade and to keep your resources in sync with terraform.

**Comment by vitulrana** [comment]
> @vitulrana Run `terraform plan` to sync the resources and then paste the **integration_key** and **webhook_url** in the resource block. This is required to support version upgrade and to keep your resources in sync with terraform.

@dheeruk12 We have already terraform plan and apply.

**Comment by dheeruk12** [comment]
> > @vitulrana Run `terraform plan` to sync the resources and then paste the **integration_key** and **webhook_url** in the resource block. This is required to support version upgrade and to keep your resources in sync with terraform.
> 
> @dheeruk12 We have already terraform plan and apply.

@vitulrana paste the integration_key and webhook_url in the  resource block that will solve

**Comment by vitulrana** [comment]
> > > @vitulrana Run `terraform plan` to sync the resources and then paste the **integration_key** and **webhook_url** in the resource block. This is required to support version upgrade and to keep your resources in sync with terraform.
> > 
> > 
> > @dheeruk12 We have already terraform plan and apply.
> 
> @vitulrana paste the integration_key and webhook_url in the resource block that will solve

@dheeruk12 We are not talking about import here, we have just upgraded the version, So, I really don't need to paste anything.

**Comment by vitulrana** [comment]
I don't think you are understanding that when I am creating integration via terraform and it's an automation code for multiple services, I can't go and put key and webhook_url for each service as it's just one module which is getting used.

**Comment by deepakzenduty** [comment]
[v0.1.8](https://github.com/Zenduty/terraform-provider-zenduty/tree/v0.1.8) it will fix the issue
