### ISSUE TITLE
Inadequate terraform import documentation and examples.

### ISSUE THREAD

**Issue by dariothornhill** [Zenduty/terraform-provider-zenduty#5]
#### Description
There is insufficient documentation about the import feature of the zenduty provider.

#### Example
A simple starting point could look something like the [Azure Provider import section
](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/availability_set#import)

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [  ] Add import example for each resource
- [  ] Add notes for resources which cannot be imported

**Comment by deepakzenduty** [comment]
into the pipeline, we will update it soon .
